package com.Eamcet.predictor.model;

import jakarta.persistence.*;
import java.util.Objects;

/**
 * Entity class representing a college in the EAMCET predictor system.
 * This class maps to the 'raw_table' database table and contains all the information
 * about colleges including cutoff ranks for different categories, placement information,
 * and location details.
 */
@Entity
@Table(name = "raw_table")
public class College
{

    /**
     * Primary key for the college entity, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer sno;

    /**
     * Institution code uniquely identifying the college.
     */
    @Column(name = "instcode")
    private String instcode;

    /**
     * Full name of the institution.
     */
    @Column(name = "institution_name")
    private String institution_name;

    /**
     * Division information of the college.
     */
    @Column(name = "division")
    private String division;

    /**
     * Region where the college is located (e.g., AU, SVU, SW).
     */
    @Column(name = "region")
    private String region;

    /**
     * District where the college is located.
     */
    @Column(name = "dist")
    private String district;

    /**
     * Place/locality where the college is located.
     */
    private String place;
    
    /**
     * Affiliation information of the college.
     */
    private String affl;

    /**
     * Branch code representing the engineering branch (e.g., CSE, ECE).
     */
    @Column(name = "branch_code")
    private String branchCode;

    /**
     * Tier classification of the college (e.g., Tier 1, Tier 2, Tier 3).
     */
    @Column(name = "tier")
    private String tier;

    /**
     * Highest package offered to students during placements.
     */
    @Column(name = "highest_package")
    private Double highestPackage;

    /**
     * Average package offered to students during placements.
     */
    @Column(name = "average_package")
    private Double averagePackage;

    /**
     * Quality rating of the placement drive (e.g., Excellent, Very Good, Good, Bad).
     */
    @Column(name = "placement_drive_quality")
    private String placementDriveQuality;

    // Cutoff ranks for different categories
    
    /**
     * Cutoff rank for OC (Open Category) boys.
     */
    @Column(name = "oc_boys")
    private Integer ocBoys;
    
    /**
     * Cutoff rank for OC (Open Category) girls.
     */
    @Column(name = "oc_girls")
    private Integer ocGirls;
    
    /**
     * Cutoff rank for SC (Scheduled Caste) boys.
     */
    @Column(name = "sc_boys")
    private Integer scBoys;
    
    /**
     * Cutoff rank for SC (Scheduled Caste) girls.
     */
    @Column(name = "sc_girls")
    private Integer scGirls;
    
    /**
     * Cutoff rank for ST (Scheduled Tribe) boys.
     */
    @Column(name = "st_boys")
    private Integer stBoys;
    
    /**
     * Cutoff rank for ST (Scheduled Tribe) girls.
     */
    @Column(name = "st_girls")
    private Integer stGirls;
    
    /**
     * Cutoff rank for BC-A boys.
     */
    @Column(name = "bca_boys")
    private Integer bcaBoys;
    
    /**
     * Cutoff rank for BC-A girls.
     */
    @Column(name = "bca_girls")
    private Integer bcaGirls;
    
    /**
     * Cutoff rank for BC-B boys.
     */
    @Column(name = "bcb_boys")
    private Integer bcbBoys;
    
    /**
     * Cutoff rank for BC-B girls.
     */
    @Column(name = "bcb_girls")
    private Integer bcbGirls;
    
    /**
     * Cutoff rank for BC-C boys.
     */
    @Column(name = "bcc_boys")
    private Integer bccBoys;
    
    /**
     * Cutoff rank for BC-C girls.
     */
    @Column(name = "bcc_girls")
    private Integer bccGirls;
    
    /**
     * Cutoff rank for BC-D boys.
     */
    @Column(name = "bcd_boys")
    private Integer bcdBoys;
    
    /**
     * Cutoff rank for BC-D girls.
     */
    @Column(name = "bcd_girls")
    private Integer bcdGirls;
    
    /**
     * Cutoff rank for BC-E boys.
     */
    @Column(name = "bce_boys")
    private Integer bceBoys;
    
    /**
     * Cutoff rank for BC-E girls.
     */
    @Column(name = "bce_girls")
    private Integer bceGirls;
    
    /**
     * Cutoff rank for OC (EWS Quota) boys.
     */
    @Column(name = "oc_ews_boys")
    private Integer ocEwsBoys;
    
    /**
     * Cutoff rank for OC (EWS Quota) girls.
     */
    @Column(name = "oc_ews_girls")
    private Integer ocEwsGirls;

    /**
     * Default constructor required by JPA.
     */
    public College()
    {
    }

    // Getter and setter methods for all fields
    
    /**
     * Gets the serial number (primary key) of the college.
     * 
     * @return The serial number
     */
    public Integer getSno()
    {
        return sno;
    }
    
    /**
     * Sets the serial number (primary key) of the college.
     * 
     * @param sno The serial number to set
     */
    public void setSno(Integer sno)
    {
        this.sno = sno;
    }
    
    /**
     * Gets the institution code of the college.
     * 
     * @return The institution code
     */
    public String getInstcode()
    {
        return instcode;
    }
    
    /**
     * Sets the institution code of the college.
     * 
     * @param instcode The institution code to set
     */
    public void setInstcode(String instcode)
    {
        this.instcode = instcode;
    }
    
    /**
     * Gets the institution name.
     * 
     * @return The institution name
     */
    public String getInstitution_name()
    {
        return institution_name;
    }
    
    /**
     * Sets the institution name.
     * 
     * @param institution_name The institution name to set
     */
    public void setInstitution_name(String institution_name)
    {
        this.institution_name = institution_name;
    }
    
    /**
     * Gets the division information.
     * 
     * @return The division
     */
    public String getDivision()
    {
        return division;
    }
    
    /**
     * Sets the division information.
     * 
     * @param division The division to set
     */
    public void setDivision(String division)
    {
        this.division = division;
    }
    
    /**
     * Gets the region where the college is located.
     * 
     * @return The region
     */
    public String getRegion()
    {
        return region;
    }
    
    /**
     * Sets the region where the college is located.
     * 
     * @param region The region to set
     */
    public void setRegion(String region)
    {
        this.region = region;
    }
    
    /**
     * Gets the district where the college is located.
     * 
     * @return The district
     */
    public String getDistrict()
    {
        return district;
    }
    
    /**
     * Sets the district where the college is located.
     * 
     * @param district The district to set
     */
    public void setDistrict(String district)
    {
        this.district = district;
    }
    
    /**
     * Gets the place/locality where the college is located.
     * 
     * @return The place
     */
    public String getPlace()
    {
        return place;
    }
    
    /**
     * Sets the place/locality where the college is located.
     * 
     * @param place The place to set
     */
    public void setPlace(String place)
    {
        this.place = place;
    }
    
    /**
     * Gets the affiliation information.
     * 
     * @return The affiliation
     */
    public String getAffl()
    {
        return affl;
    }
    
    /**
     * Sets the affiliation information.
     * 
     * @param affl The affiliation to set
     */
    public void setAffl(String affl)
    {
        this.affl = affl;
    }
    
    /**
     * Gets the branch code.
     * 
     * @return The branch code
     */
    public String getBranchCode()
    {
        return branchCode;
    }
    
    /**
     * Sets the branch code.
     * 
     * @param branchCode The branch code to set
     */
    public void setBranchCode(String branchCode)
    {
        this.branchCode = branchCode;
    }
    
    /**
     * Gets the tier classification.
     * 
     * @return The tier
     */
    public String getTier()
    {
        return tier;
    }
    
    /**
     * Sets the tier classification.
     * 
     * @param tier The tier to set
     */
    public void setTier(String tier)
    {
        this.tier = tier;
    }

    /**
     * Gets the highest package offered during placements.
     * 
     * @return The highest package
     */
    public Double getHighestPackage()
    {
        return highestPackage;
    }
    
    /**
     * Sets the highest package offered during placements.
     * 
     * @param highestPackage The highest package to set
     */
    public void setHighestPackage(Double highestPackage)
    {
        this.highestPackage = highestPackage;
    }
    
    /**
     * Gets the average package offered during placements.
     * 
     * @return The average package
     */
    public Double getAveragePackage()
    {
        return averagePackage;
    }
    
    /**
     * Sets the average package offered during placements.
     * 
     * @param averagePackage The average package to set
     */
    public void setAveragePackage(Double averagePackage)
    {
        this.averagePackage = averagePackage;
    }
    
    /**
     * Gets the placement drive quality rating.
     * 
     * @return The placement drive quality
     */
    public String getPlacementDriveQuality()
    {
        return placementDriveQuality;
    }
    
    /**
     * Sets the placement drive quality rating.
     * 
     * @param placementDriveQuality The placement drive quality to set
     */
    public void setPlacementDriveQuality(String placementDriveQuality)
    {
        this.placementDriveQuality = placementDriveQuality;
    }

    /**
     * Gets the cutoff rank for OC boys.
     * 
     * @return The OC boys cutoff rank
     */
    public Integer getOcBoys()
    {
        return ocBoys;
    }
    
    /**
     * Sets the cutoff rank for OC boys.
     * 
     * @param ocBoys The OC boys cutoff rank to set
     */
    public void setOcBoys(Integer ocBoys)
    {
        this.ocBoys = ocBoys;
    }
    
    /**
     * Gets the cutoff rank for OC girls.
     * 
     * @return The OC girls cutoff rank
     */
    public Integer getOcGirls()
    {
        return ocGirls;
    }
    
    /**
     * Sets the cutoff rank for OC girls.
     * 
     * @param ocGirls The OC girls cutoff rank to set
     */
    public void setOcGirls(Integer ocGirls)
    {
        this.ocGirls = ocGirls;
    }
    
    /**
     * Gets the cutoff rank for SC boys.
     * 
     * @return The SC boys cutoff rank
     */
    public Integer getScBoys()
    {
        return scBoys;
    }
    
    /**
     * Sets the cutoff rank for SC boys.
     * 
     * @param scBoys The SC boys cutoff rank to set
     */
    public void setScBoys(Integer scBoys)
    {
        this.scBoys = scBoys;
    }
    
    /**
     * Gets the cutoff rank for SC girls.
     * 
     * @return The SC girls cutoff rank
     */
    public Integer getScGirls()
    {
        return scGirls;
    }
    
    /**
     * Sets the cutoff rank for SC girls.
     * 
     * @param scGirls The SC girls cutoff rank to set
     */
    public void setScGirls(Integer scGirls)
    {
        this.scGirls = scGirls;
    }
    
    /**
     * Gets the cutoff rank for ST boys.
     * 
     * @return The ST boys cutoff rank
     */
    public Integer getStBoys()
    {
        return stBoys;
    }
    
    /**
     * Sets the cutoff rank for ST boys.
     * 
     * @param stBoys The ST boys cutoff rank to set
     */
    public void setStBoys(Integer stBoys)
    {
        this.stBoys = stBoys;
    }
    
    /**
     * Gets the cutoff rank for ST girls.
     * 
     * @return The ST girls cutoff rank
     */
    public Integer getStGirls()
    {
        return stGirls;
    }
    
    /**
     * Sets the cutoff rank for ST girls.
     * 
     * @param stGirls The ST girls cutoff rank to set
     */
    public void setStGirls(Integer stGirls)
    {
        this.stGirls = stGirls;
    }
    
    /**
     * Gets the cutoff rank for BC-A boys.
     * 
     * @return The BC-A boys cutoff rank
     */
    public Integer getBcaBoys()
    {
        return bcaBoys;
    }
    
    /**
     * Sets the cutoff rank for BC-A boys.
     * 
     * @param bcaBoys The BC-A boys cutoff rank to set
     */
    public void setBcaBoys(Integer bcaBoys)
    {
        this.bcaBoys = bcaBoys;
    }
    
    /**
     * Gets the cutoff rank for BC-A girls.
     * 
     * @return The BC-A girls cutoff rank
     */
    public Integer getBcaGirls()
    {
        return bcaGirls;
    }
    
    /**
     * Sets the cutoff rank for BC-A girls.
     * 
     * @param bcaGirls The BC-A girls cutoff rank to set
     */
    public void setBcaGirls(Integer bcaGirls)
    {
        this.bcaGirls = bcaGirls;
    }
    
    /**
     * Gets the cutoff rank for BC-B boys.
     * 
     * @return The BC-B boys cutoff rank
     */
    public Integer getBcbBoys()
    {
        return bcbBoys;
    }
    
    /**
     * Sets the cutoff rank for BC-B boys.
     * 
     * @param bcbBoys The BC-B boys cutoff rank to set
     */
    public void setBcbBoys(Integer bcbBoys)
    {
        this.bcbBoys = bcbBoys;
    }
    
    /**
     * Gets the cutoff rank for BC-B girls.
     * 
     * @return The BC-B girls cutoff rank
     */
    public Integer getBcbGirls()
    {
        return bcbGirls;
    }
    
    /**
     * Sets the cutoff rank for BC-B girls.
     * 
     * @param bcbGirls The BC-B girls cutoff rank to set
     */
    public void setBcbGirls(Integer bcbGirls)
    {
        this.bcbGirls = bcbGirls;
    }
    
    /**
     * Gets the cutoff rank for BC-C boys.
     * 
     * @return The BC-C boys cutoff rank
     */
    public Integer getBccBoys()
    {
        return bccBoys;
    }
    
    /**
     * Sets the cutoff rank for BC-C boys.
     * 
     * @param bccBoys The BC-C boys cutoff rank to set
     */
    public void setBccBoys(Integer bccBoys)
    {
        this.bccBoys = bccBoys;
    }
    
    /**
     * Gets the cutoff rank for BC-C girls.
     * 
     * @return The BC-C girls cutoff rank
     */
    public Integer getBccGirls()
    {
        return bccGirls;
    }
    
    /**
     * Sets the cutoff rank for BC-C girls.
     * 
     * @param bccGirls The BC-C girls cutoff rank to set
     */
    public void setBccGirls(Integer bccGirls)
    {
        this.bccGirls = bccGirls;
    }
    
    /**
     * Gets the cutoff rank for BC-D boys.
     * 
     * @return The BC-D boys cutoff rank
     */
    public Integer getBcdBoys()
    {
        return bcdBoys;
    }
    
    /**
     * Sets the cutoff rank for BC-D boys.
     * 
     * @param bcdBoys The BC-D boys cutoff rank to set
     */
    public void setBcdBoys(Integer bcdBoys)
    {
        this.bcdBoys = bcdBoys;
    }
    
    /**
     * Gets the cutoff rank for BC-D girls.
     * 
     * @return The BC-D girls cutoff rank
     */
    public Integer getBcdGirls()
    {
        return bcdGirls;
    }
    
    /**
     * Sets the cutoff rank for BC-D girls.
     * 
     * @param bcdGirls The BC-D girls cutoff rank to set
     */
    public void setBcdGirls(Integer bcdGirls)
    {
        this.bcdGirls = bcdGirls;
    }
    
    /**
     * Gets the cutoff rank for BC-E boys.
     * 
     * @return The BC-E boys cutoff rank
     */
    public Integer getBceBoys()
    {
        return bceBoys;
    }
    
    /**
     * Sets the cutoff rank for BC-E boys.
     * 
     * @param bceBoys The BC-E boys cutoff rank to set
     */
    public void setBceBoys(Integer bceBoys)
    {
        this.bceBoys = bceBoys;
    }
    
    /**
     * Gets the cutoff rank for BC-E girls.
     * 
     * @return The BC-E girls cutoff rank
     */
    public Integer getBceGirls()
    {
        return bceGirls;
    }
    
    /**
     * Sets the cutoff rank for BC-E girls.
     * 
     * @param bceGirls The BC-E girls cutoff rank to set
     */
    public void setBceGirls(Integer bceGirls)
    {
        this.bceGirls = bceGirls;
    }
    
    /**
     * Gets the cutoff rank for OC EWS boys.
     * 
     * @return The OC EWS boys cutoff rank
     */
    public Integer getOcEwsBoys()
    {
        return ocEwsBoys;
    }
    
    /**
     * Sets the cutoff rank for OC EWS boys.
     * 
     * @param ocEwsBoys The OC EWS boys cutoff rank to set
     */
    public void setOcEwsBoys(Integer ocEwsBoys)
    {
        this.ocEwsBoys = ocEwsBoys;
    }
    
    /**
     * Gets the cutoff rank for OC EWS girls.
     * 
     * @return The OC EWS girls cutoff rank
     */
    public Integer getOcEwsGirls()
    {
        return ocEwsGirls;
    }
    
    /**
     * Sets the cutoff rank for OC EWS girls.
     * 
     * @param ocEwsGirls The OC EWS girls cutoff rank to set
     */
    public void setOcEwsGirls(Integer ocEwsGirls)
    {
        this.ocEwsGirls = ocEwsGirls;
    }

    /**
     * Returns a string representation of the College object.
     * 
     * @return String representation containing key college information
     */
    @Override
    public String toString() {
        return "College{" +
                "sno=" + sno +
                ", instcode='" + instcode + '\'' +
                ", institution_name='" + institution_name + '\'' +
                ", district='" + district + '\'' +
                ", region='" + region + '\'' +
                ", branchCode='" + branchCode + '\'' +
                ", division='" + division + '\'' +
                ", tier='" + tier + '\'' +
                '}';
    }

    /**
     * Checks if this College object is equal to another object.
     * Two College objects are considered equal if they have the same sno and instcode.
     * 
     * @param o The object to compare with
     * @return true if the objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        College college = (College) o;
        return Objects.equals(sno, college.sno) &&
                Objects.equals(instcode, college.instcode);
    }

    /**
     * Returns a hash code value for the College object.
     * The hash code is based on the sno and instcode fields.
     * 
     * @return The hash code value
     */
    @Override
    public int hashCode() {
        return Objects.hash(sno, instcode);
    }
}