services:
  - type: web
    name: college-predictor-backend
    runtime: docker
    repo: https://github.com/sreemani0323/CollegePredictor420
    rootDir: BackEnd_Predictor/predictor
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /ping
    envVars:
      - key: DB_PASSWORD
        sync: false
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
    buildCommand: ""
    startCommand: ""
